quickstarts/scale-with-dask.ipynb

I found what looks to be a typo on the `scale-with-dask` example and I decided to make a minor contribution fixing it. BTW, the Planetary Computer is amazing 🚀

Proofreading of `scale-with-dask`

---

tutorials/cloudless-mosaic-sentinel2.ipynb

Number of items returned by query did not match comment in mosaic notebook, fixed.

Comment change in mosaic notebook

---

datasets/sentinel-2-l2a/sentinel-2-l2a-example.ipynb

Fixes the demo (cc @agentmorris). We'll still want to update the STAC items or restore the 20m file.

Use 10m resolution data

---

.pre-commit-config.yaml
CONTRIBUTING.md
competitions/s1floods/generate_auxiliary_input.ipynb
scripts/check_headers.py
tutorials/surface_analysis.ipynb

Verifies that we have one and only one H2 and no H1s.

Add pre-commit check for headers

---

tutorials/hurricane-florence-animation.ipynb

Hopefully this syntax makes everyone happy

Close video tag again

---

quickstarts/reading-tabular-data.ipynb

Updates this notebook to use the STAC API, rather than hardcoded URLs.

Use STAC metadata for reading-tabular-data

---

tutorials/hurricane-florence-animation.ipynb

Removed the white padding around the image.

Improved hurricane Florence animation

---

datasets/gbif/gbif-example.ipynb

Works around a rendering bug from headers with no text.

Fixed GBIF example on docs site

---

quickstarts/using-radiant-mlhub-api.ipynb
scripts/check_headers.py

The previous check failed if the header wasn't the first text in the cell. Switched to a regex approach.

Fixup headers

---

datasets/gbif/gbif-example.ipynb

xref https://github.com/dask/dask/issues/8491

Updated gbif example notebook

---

tutorials/zonal_statistics.ipynb

Updates zonal for a change in stackstac that disallows invalid nodata
values to mosaic.

Upstream change in stackstac

---

README.md
quickstarts/leafmap-example.ipynb

Blocked by an update to planetary-computer-containers with leafmap>=0.7.6. That's incoming shortly.

Leafmap example

---

tutorials/landcover.ipynb

Temporary fix for this missing library. xref #149

Include stac-vrt install

---

datasets/sentinel-1-rtc/sentinel-1-rtc-example.ipynb

This puts the HTML / javascript loading in the markdown
content for the RTC example.

Embed javascript for s1-rtc example

---

datasets/sentinel-1-rtc/sentinel-1-rtc-example.ipynb

This didn't fix it on planetarycomputer.microsoft.com, and double-embedded stuff on nbviewer. Trying other ways.

Remove JS embedded in markdown

---

README.md

Add notebook showing the radiometric terrain correction assessment.

Add Radiometric terrain correction qualitative assessment 

---

quickstarts/scale-with-dask.ipynb

See the discussion in https://github.com/microsoft/PlanetaryComputer/discussions/94.

Added dask client note

---

datasets/cil-gdpcir/cil-gdpcir-example.ipynb
datasets/cil-gdpcir/ensemble.ipynb

See https://github.com/ClimateImpactLab/downscaleCMIP6/pull/637/files

Updated notebooks for cil-gdpcir license

---

quickstarts/using-the-data-api.ipynb

xref https://github.com/microsoft/PlanetaryComputer/discussions/276

Updated URL quoting for data API example

---

datasets/nasadem/nasadem-example.ipynb
quickstarts/storage.ipynb
tutorials/coregistration.ipynb
tutorials/local-tools.ipynb
tutorials/ndvi_hotspots.ipynb
tutorials/proximity_tools.ipynb
tutorials/reprojection.ipynb
tutorials/surface_analysis.ipynb
tutorials/zonal_statistics.ipynb

Fixed broken links to xarray-spatial.readthedocs.io
